--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Alemiz112/WaterGate-Atlantis
branches:
- master
- atlantis-netty
- pmmp-4
projects:
  WaterGate-Atlantis:
    path: ""
    icon: "icon.png"
...
